import type { Config } from 'tailwindcss';

export default {
    darkMode: ['class'],
    content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
    theme: {
        container: {
            center: true,
            padding: '2rem',
            screens: {
                '2xl': '1400px',
            },
        },
        extend: {
            colors: {
                border: 'hsl(var(--border))',
                input: 'hsl(var(--input))',
                ring: 'hsl(var(--ring))',
                background: 'hsl(var(--background))',
                foreground: 'hsl(var(--foreground))',
                primary: {
                    DEFAULT: 'hsl(var(--primary))',
                    foreground: 'hsl(var(--primary-foreground))',
                },
                secondary: {
                    DEFAULT: 'hsl(var(--secondary))',
                    foreground: 'hsl(var(--secondary-foreground))',
                },
                destructive: {
                    DEFAULT: 'hsl(var(--destructive))',
                    foreground: 'hsl(var(--destructive-foreground))',
                },
                muted: {
                    DEFAULT: 'hsl(var(--muted))',
                    foreground: 'hsl(var(--muted-foreground))',
                },
                accent: {
                    DEFAULT: 'hsl(var(--accent))',
                    foreground: 'hsl(var(--accent-foreground))',
                },
                popover: {
                    DEFAULT: 'hsl(var(--popover))',
                    foreground: 'hsl(var(--popover-foreground))',
                },
                card: {
                    DEFAULT: 'hsl(var(--card))',
                    foreground: 'hsl(var(--card-foreground))',
                },
            },
            borderRadius: {
                lg: 'var(--radius)',
                md: 'calc(var(--radius) - 2px)',
                sm: 'calc(var(--radius) - 4px)',
            },
        },
    },
    plugins: [require('daisyui')],
    daisyui: {
        themes: [
            {
                light: {
                    ...require('daisyui/src/theming/themes')['light'],
                    primary: 'hsl(221.2, 83.2%, 53.3%)',
                    'primary-content': 'hsl(210, 40%, 98%)',
                    secondary: 'hsl(210, 40%, 96.1%)',
                    'secondary-content': 'hsl(222.2, 47.4%, 11.2%)',
                    accent: 'hsl(210, 40%, 96.1%)',
                    'accent-content': 'hsl(222.2, 47.4%, 11.2%)',
                    neutral: 'hsl(222.2, 84%, 4.9%)',
                    'neutral-content': 'hsl(210, 40%, 98%)',
                    'base-100': 'hsl(0, 0%, 100%)',
                    'base-200': 'hsl(210, 40%, 96.1%)',
                    'base-300': 'hsl(214.3, 31.8%, 91.4%)',
                    'base-content': 'hsl(222.2, 84%, 4.9%)',
                    info: 'hsl(221.2, 83.2%, 53.3%)',
                    success: 'hsl(142.1, 76.2%, 36.3%)',
                    warning: 'hsl(38, 92%, 50%)',
                    error: 'hsl(0, 84.2%, 60.2%)',
                },
                dark: {
                    ...require('daisyui/src/theming/themes')['dark'],
                    primary: 'hsl(217.2, 91.2%, 59.8%)',
                    'primary-content': 'hsl(222.2, 47.4%, 11.2%)',
                    secondary: 'hsl(217.2, 32.6%, 17.5%)',
                    'secondary-content': 'hsl(210, 40%, 98%)',
                    accent: 'hsl(217.2, 32.6%, 17.5%)',
                    'accent-content': 'hsl(210, 40%, 98%)',
                    neutral: 'hsl(222.2, 84%, 4.9%)',
                    'neutral-content': 'hsl(210, 40%, 98%)',
                    'base-100': 'hsl(222.2, 84%, 4.9%)',
                    'base-200': 'hsl(217.2, 32.6%, 17.5%)',
                    'base-300': 'hsl(217.2, 32.6%, 17.5%)',
                    'base-content': 'hsl(210, 40%, 98%)',
                    info: 'hsl(217.2, 91.2%, 59.8%)',
                    success: 'hsl(142.1, 76.2%, 36.3%)',
                    warning: 'hsl(38, 92%, 50%)',
                    error: 'hsl(0, 62.8%, 30.6%)',
                },
                midnight: {
                    ...require('daisyui/src/theming/themes')['dark'],
                    primary: 'hsl(263, 70%, 58%)',
                    'primary-content': 'hsl(226, 100%, 94%)',
                    secondary: 'hsl(235, 30%, 15%)',
                    'secondary-content': 'hsl(226, 100%, 94%)',
                    accent: 'hsl(263, 50%, 20%)',
                    'accent-content': 'hsl(226, 100%, 94%)',
                    neutral: 'hsl(235, 35%, 5%)',
                    'neutral-content': 'hsl(226, 100%, 94%)',
                    'base-100': 'hsl(235, 35%, 5%)',
                    'base-200': 'hsl(235, 30%, 15%)',
                    'base-300': 'hsl(235, 25%, 18%)',
                    'base-content': 'hsl(226, 100%, 94%)',
                    info: 'hsl(263, 70%, 58%)',
                    success: 'hsl(142.1, 76.2%, 36.3%)',
                    warning: 'hsl(38, 92%, 50%)',
                    error: 'hsl(0, 62.8%, 30.6%)',
                },
                emerald: {
                    ...require('daisyui/src/theming/themes')['dark'],
                    primary: 'hsl(160, 60%, 45%)',
                    'primary-content': 'hsl(155, 30%, 4%)',
                    secondary: 'hsl(155, 25%, 13%)',
                    'secondary-content': 'hsl(152, 80%, 92%)',
                    accent: 'hsl(160, 40%, 18%)',
                    'accent-content': 'hsl(152, 80%, 92%)',
                    neutral: 'hsl(155, 30%, 4%)',
                    'neutral-content': 'hsl(152, 80%, 92%)',
                    'base-100': 'hsl(155, 30%, 4%)',
                    'base-200': 'hsl(155, 25%, 13%)',
                    'base-300': 'hsl(155, 20%, 16%)',
                    'base-content': 'hsl(152, 80%, 92%)',
                    info: 'hsl(160, 60%, 45%)',
                    success: 'hsl(142.1, 76.2%, 36.3%)',
                    warning: 'hsl(38, 92%, 50%)',
                    error: 'hsl(0, 62.8%, 30.6%)',
                },
                sunset: {
                    ...require('daisyui/src/theming/themes')['dark'],
                    primary: 'hsl(38, 70%, 50%)',
                    'primary-content': 'hsl(25, 30%, 5%)',
                    secondary: 'hsl(25, 25%, 14%)',
                    'secondary-content': 'hsl(35, 80%, 92%)',
                    accent: 'hsl(38, 40%, 18%)',
                    'accent-content': 'hsl(35, 80%, 92%)',
                    neutral: 'hsl(25, 30%, 5%)',
                    'neutral-content': 'hsl(35, 80%, 92%)',
                    'base-100': 'hsl(25, 30%, 5%)',
                    'base-200': 'hsl(25, 25%, 14%)',
                    'base-300': 'hsl(25, 20%, 17%)',
                    'base-content': 'hsl(35, 80%, 92%)',
                    info: 'hsl(38, 70%, 50%)',
                    success: 'hsl(142.1, 76.2%, 36.3%)',
                    warning: 'hsl(38, 92%, 50%)',
                    error: 'hsl(0, 62.8%, 30.6%)',
                },
                charcoal: {
                    ...require('daisyui/src/theming/themes')['dark'],
                    primary: 'hsl(0, 0%, 60%)',
                    'primary-content': 'hsl(0, 0%, 5%)',
                    secondary: 'hsl(0, 0%, 14%)',
                    'secondary-content': 'hsl(0, 0%, 92%)',
                    accent: 'hsl(0, 0%, 18%)',
                    'accent-content': 'hsl(0, 0%, 92%)',
                    neutral: 'hsl(0, 0%, 5%)',
                    'neutral-content': 'hsl(0, 0%, 92%)',
                    'base-100': 'hsl(0, 0%, 5%)',
                    'base-200': 'hsl(0, 0%, 14%)',
                    'base-300': 'hsl(0, 0%, 17%)',
                    'base-content': 'hsl(0, 0%, 92%)',
                    info: 'hsl(0, 0%, 60%)',
                    success: 'hsl(142.1, 76.2%, 36.3%)',
                    warning: 'hsl(38, 92%, 50%)',
                    error: 'hsl(0, 62.8%, 30.6%)',
                },
            },
        ],
        darkTheme: 'dark',
        base: true,
        styled: true,
        utils: true,
    },
} satisfies Config;
